<?php

namespace Rol\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getApplicationWithAdvert($limit)
    {
        $qb =$this
            ->createQueryBuilder('a')
            ->join('a.Advert','adv')
            ->addSelect('adv')
        ;
        $qb->setMaxResults($limit);
        
        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
}
